# Sidebar navigation

- label: 'Welcome'
  link: '/'
- label: 'Getting Started'
  link: '/getting-started'
- label: 'Cloud Skills Challenge: Get Ready for MLSS'
  link: /faq

- label: Azure Machine Learing
  items:
    - label: 'Running python notebooks'
      link: '/usage/creating-docs'
    - label: 'Day 2: Clinical Statistics'
      link: '/usage/navigation'
    - label: 'Day 3: Time Series'
      link: '/usage/shadowing'
    - label: 'Day 4: Climate'
      link: '/usage/using-yaml-files'
    - label: 'Day 5: Climate'
      link: '/usage/using-yaml-files'
    - label: 'Day 6: -omics'
      link: '/usage/using-yaml-files'
    - label: 'Day 7: Presentation'
      link: '/usage/using-yaml-files'

- label: Get Microsoft Certified
  items:
    - label: 'Certifications for Students and Teachers'
      link: /faq
    - label: 'Certifications for Professionals'
      link: /faq
    - label: 'Get your MLSS 2022 Digital Badge'
      link: /faq
