# Sidebar navigation

- label: 'Welcome'
  link: '/'
- label: 'Getting Started'
  link: '/getting-started'

- label: 'Timeline'
  link: /timeline

- label: 'Contacts'
  link: /contacts


- label: Skill-up on Azure Cloud
  items:
    - label: "Join our Cloud Skills challenge"
      link: /skillchallenge
    - label: "Microsoft Learning Paths and Certifications"
      link: /learningpaths


- label: Using Azure Machine Learing
  items:
    #- label: 'Running python notebooks'
    #  link: /usage/aml_run_notebooks

    - label: 'Clinical Statistics'
      link: '/usage/aml_statistics'

    #- label: 'Day 3: Time Series'
    #  link: '/usage/aml_time_series'
    # - label: 'Day 4: Climate'
    #   link: '/usage/aml_climate'
    # - label: 'Day 5: Imaging'
    #   link: 'usage/aml_imaging'
    # - label: 'Day 6: omics'
    #   link: '/usage/aml_omics'
    # - label: 'Day 7: Presentation'
    #   link: '/usage/aml_presentation'

